### ISSUE TITLE
How does one use this plug in?

### ISSUE THREAD

**Issue by mangelozzi** [roobert/surround-ui.nvim#5]
I know how to use nvim-surround fairly well, and I use which-key, but can't get this plug in to do anything. What is the trigger to making it appear? I cant tell from studying the animated give, and pressing `S` does nothing, also tried `ySiw` dont know what else to try. 
Sorry I dont seem smart enough to figure it out. Please would you add a description to the readme.md

**Comment by roobert** [comment]
Hi Mangelozzi,

This plugin is triggered with `<leader>-S`. The leader key is a special key in vim that acts as a prefix for user-definer or plugin-defined shortcuts. You can find out what your leader key is by typing: `:let mapleader`.

Hope this helps!

**Comment by mangelozzi** [comment]
Thanks so much, I didnt realize I need to use the `<leader>` before the mapping. It's working well for me now, very neat!

PS I noticed it doesn't list tag:

e.g.
`ysiwt -> div`
or
`csiwt -> span`
